# Base ORM Model for Larapak (Eloquent-like)

from .database import db_manager
from .query_builder import QueryBuilder
from ngapak.vm import NgapakClass, NgapakInstance

class Model:
    active_vm = None
    tabel = None
    fillable = []

    @classmethod
    def get_table_name(cls, class_obj):
        if isinstance(class_obj, NgapakClass):
            return class_obj.attributes.get("tabel", f"{class_obj.name.lower()}s")
        return getattr(class_obj, "tabel", f"{class_obj.__name__.lower()}s")

    @classmethod
    def get_fillable(cls, class_obj):
        if isinstance(class_obj, NgapakClass):
            return class_obj.attributes.get("fillable", [])
        return getattr(class_obj, "fillable", [])

    @classmethod
    def kabeh(cls):
        # cls is the class object (e.g. NgapakClass 'User' or Model subclass)
        table = Model.get_table_name(cls)
        rows = QueryBuilder(table).kabeh()
        
        instances = []
        for row in rows:
            instance = cls() if isinstance(cls, NgapakClass) else cls.__new__(cls)
            if isinstance(instance, NgapakInstance):
                instance.fields.update(row)
            else:
                instance.__dict__.update(row)
            instances.append(instance)
        return instances

    @classmethod
    def golek(cls, record_id):
        table = Model.get_table_name(cls)
        row = QueryBuilder(table).nek("id", "==", record_id).golek()
        if not row:
            return None
            
        instance = cls() if isinstance(cls, NgapakClass) else cls.__new__(cls)
        if isinstance(instance, NgapakInstance):
            instance.fields.update(row)
        else:
            instance.__dict__.update(row)
        return instance

    @classmethod
    def gawe(cls, data):
        table = Model.get_table_name(cls)
        fillable = Model.get_fillable(cls)
        
        # Filter fields based on fillable
        filtered_data = {}
        if fillable:
            for k, v in data.items():
                if k in fillable:
                    filtered_data[k] = v
        else:
            filtered_data = data
            
        record_id = QueryBuilder(table).tambah(filtered_data)
        
        # Reload instance from DB to get autogenerated fields/defaults
        return Model.golek.__func__(cls, record_id)

    # Instance Methods
    def simpen(self):
        # self is NgapakInstance or Model subclass
        cls = self.ngapak_class if isinstance(self, NgapakInstance) else self.__class__
        table = Model.get_table_name(cls)
        
        fields = self.fields if isinstance(self, NgapakInstance) else self.__dict__
        
        if "id" in fields and fields["id"] is not None:
            # Update
            QueryBuilder(table).nek("id", "==", fields["id"]).anyari(fields)
        else:
            # Insert
            record_id = QueryBuilder(table).tambah(fields)
            fields["id"] = record_id
        return self

    def busak(self):
        cls = self.ngapak_class if isinstance(self, NgapakInstance) else self.__class__
        table = Model.get_table_name(cls)
        fields = self.fields if isinstance(self, NgapakInstance) else self.__dict__
        
        if "id" in fields and fields["id"] is not None:
            QueryBuilder(table).nek("id", "==", fields["id"]).busak()
            fields["id"] = None
        return self

    # Relationship Methods
    def hasOne(self, related_class_name, foreign_key=None, local_key="id"):
        if not Model.active_vm:
            return None
            
        related_class = Model.active_vm.globals.get(related_class_name)
        if not related_class:
            raise ValueError(f"Model '{related_class_name}' tidak ditemukan di VM globals.")
            
        related_table = Model.get_table_name(related_class)
        
        # Resolve foreign key
        cls = self.ngapak_class if isinstance(self, NgapakInstance) else self.__class__
        if foreign_key is None:
            foreign_key = f"{cls.name.lower()}_id"
            
        fields = self.fields if isinstance(self, NgapakInstance) else self.__dict__
        local_val = fields.get(local_key)
        
        row = QueryBuilder(related_table).nek(foreign_key, "==", local_val).golek()
        if not row:
            return None
            
        instance = related_class() if isinstance(related_class, NgapakClass) else related_class.__new__(related_class)
        if isinstance(instance, NgapakInstance):
            instance.fields.update(row)
        else:
            instance.__dict__.update(row)
        return instance

    def hasMany(self, related_class_name, foreign_key=None, local_key="id"):
        if not Model.active_vm:
            return []
            
        related_class = Model.active_vm.globals.get(related_class_name)
        if not related_class:
            raise ValueError(f"Model '{related_class_name}' tidak ditemukan di VM globals.")
            
        related_table = Model.get_table_name(related_class)
        
        # Resolve foreign key
        cls = self.ngapak_class if isinstance(self, NgapakInstance) else self.__class__
        if foreign_key is None:
            foreign_key = f"{cls.name.lower()}_id"
            
        fields = self.fields if isinstance(self, NgapakInstance) else self.__dict__
        local_val = fields.get(local_key)
        
        rows = QueryBuilder(related_table).nek(foreign_key, "==", local_val).kabeh()
        
        instances = []
        for row in rows:
            instance = related_class() if isinstance(related_class, NgapakClass) else related_class.__new__(related_class)
            if isinstance(instance, NgapakInstance):
                instance.fields.update(row)
            else:
                instance.__dict__.update(row)
            instances.append(instance)
        return instances

    def belongsTo(self, related_class_name, foreign_key=None, owner_key="id"):
        if not Model.active_vm:
            return None
            
        related_class = Model.active_vm.globals.get(related_class_name)
        if not related_class:
            raise ValueError(f"Model '{related_class_name}' tidak ditemukan di VM globals.")
            
        related_table = Model.get_table_name(related_class)
        
        # Resolve foreign key
        if foreign_key is None:
            foreign_key = f"{related_class_name.lower()}_id"
            
        fields = self.fields if isinstance(self, NgapakInstance) else self.__dict__
        foreign_val = fields.get(foreign_key)
        
        row = QueryBuilder(related_table).nek(owner_key, "==", foreign_val).golek()
        if not row:
            return None
            
        instance = related_class() if isinstance(related_class, NgapakClass) else related_class.__new__(related_class)
        if isinstance(instance, NgapakInstance):
            instance.fields.update(row)
        else:
            instance.__dict__.update(row)
        return instance

    @classmethod
    def nek(cls, kolom, op, nilai=None):
        table = Model.get_table_name(cls)
        qb = ModelQueryBuilder(cls, table)
        return qb.nek(kolom, op, nilai)

    @classmethod
    def neng(cls, kolom, op, nilai=None):
        return cls.nek(kolom, op, nilai)


class ModelQueryBuilder(QueryBuilder):
    def __init__(self, cls, table):
        super().__init__(table)
        self.cls = cls

    def siji(self):
        row = self.golek()
        if not row:
            return None
        instance = self.cls() if isinstance(self.cls, NgapakClass) else self.cls.__new__(self.cls)
        if isinstance(instance, NgapakInstance):
            instance.fields.update(row)
        else:
            instance.__dict__.update(row)
        return instance

    def first(self):
        return self.siji()

    def kabeh(self):
        rows = super().kabeh()
        instances = []
        for row in rows:
            instance = self.cls() if isinstance(self.cls, NgapakClass) else self.cls.__new__(self.cls)
            if isinstance(instance, NgapakInstance):
                instance.fields.update(row)
            else:
                instance.__dict__.update(row)
            instances.append(instance)
        return instances

    def all(self):
        return self.kabeh()

